/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package utils;


public class StringUtils {

    private static final String MINUS_SIGN = "-";

    public boolean isPositiveNumber(String number){
        return org.apache.commons.lang3.StringUtils.isNumeric(number) &&
                !org.apache.commons.lang3.StringUtils.contains(number, MINUS_SIGN);
    }

}
